
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: ["macos-latest", "windows-2019"]
        config: ["Debug", "Release"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Tsuru ${{ matrix.config }} compilation ${{ matrix.platform }}
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . --config ${{ matrix.config }} --parallel
